### ISSUE TITLE
Get content for About Us and Contact page.

### ISSUE THREAD

**Issue by kameshsheoran** [kameshsheoran/GreenDome#2]
Provide the actual emailid and phone for support, sales etc.

**Comment by vidyasreeBT** [comment]
Simple webpage with Home page, About Us and Contact Us tabs. Please find the MainPage.zip file

**Comment by kameshsheoran** [comment]
Thanks Vidya.

Nice effort.
- I liked the About us page (colors were nice)

Few things that need to change:
- Update the font of whole web-site (Use Roboto)
- Add missing pictures.
- Add another page to your website (products page)

Use a common CSS for your first website so that if we need to change
colors/font, we can do it from single point. Using a single place to
control all the views/theme is best design pattern and lot of duplicate
effort can be avoided.

You don't need to zip the files. Just update the folder as it is.

Pull and continue your work. (Add missing pics and missing CSS). Also
update me on your JavaScript learning progress.

Dead line for all this work is Thursday evening. I expect a push by
Tomorrow EOD.

Thanks,

Good Job.
